name: Run Metryczka (z polami q1–q10)

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Skąd wziąć PDF?"
        type: choice
        options: [repo, url]
        default: repo
        required: true
      pdf_path:
        description: "Ścieżka do PDF w repo (np. metryczka_in/plik.pdf)"
        required: false
        type: string
      pdf_url:
        description: "URL do PDF (gdy mode=url)"
        required: false
        type: string
      q1:  { description: "Odpowiedź 1", required: false, type: string }
      q2:  { description: "Odpowiedź 2", required: false, type: string }
      q3:  { description: "Odpowiedź 3", required: false, type: string }
      q4:  { description: "Odpowiedź 4", required: false, type: string }
      q5:  { description: "Odpowiedź 5", required: false, type: string }
      q6:  { description: "Odpowiedź 6", required: false, type: string }
      q7:  { description: "Odpowiedź 7", required: false, type: string }
      q8:  { description: "Odpowiedź 8", required: false, type: string }
      q9:  { description: "Odpowiedź 9", required: false, type: string }
      q10: { description: "Odpowiedź 10", required: false, type: string }

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Resolve PDF (repo/url)
        run: |
          if [ "${{ inputs.mode }}" = "url" ]; then
            mkdir -p input
            curl -L "${{ inputs.pdf_url }}" -o "input/source.pdf"
            echo "PDF_PATH=input/source.pdf" >> $GITHUB_ENV
          else
            test -n "${{ inputs.pdf_path }}" || (echo "Podaj pdf_path" && exit 1)
            test -f "${{ inp
